paths:
  repos_dir: ~/repos

github:
  owner: "forbesmailler"

setup:
  gh_env_name: "setup"
  repo_visibility: "private"
  conda_channel: "conda-forge"
  default_deps:
    - python
    - invoke
    - ruff
    - pytest
    - pytest-cov
  line_length: 88
